"
---
title: TabControl object (Access)
keywords: vbaac10.chm12136
f1_keywords:
- vbaac10.chm12136
ms.prod: access
api_name:
- Access.TabControl
ms.assetid: 05f7de7b-8665-df6d-3fbb-47f8547d3baf
ms.date: 03/21/2019
localization_priority: Normal
---


# TabControl object (Access)

A tab control contains multiple pages on which you can place other controls, such as text boxes or option buttons. When a user chooses the corresponding tab, that page becomes active.


## Remarks

With the tab control, you can construct a single form or dialog box that contains several different tabs, and you can group similar options or data on each tab's page. For example, you might use a tab control on an **Employees** form to separate general and personal information.


## Events

- [Change](Access.TabControl.Change.md)
- [Click](Access.TabControl.Click.md)
- [DblClick](Access.TabControl.DblClick.md)
- [KeyDown](Access.TabControl.KeyDown.md)
- [KeyPress](Access.TabControl.KeyPress.md)
- [KeyUp](Access.TabControl.KeyUp.md)
- [MouseDown](Access.TabControl.MouseDown.md)
- [MouseMove](Access.TabControl.MouseMove.md)
- [MouseUp](Access.TabControl.MouseUp.md)

## Methods

- [Move](Access.TabControl.Move.md)
- [SizeToFit](Access.TabControl.SizeToFit.md)

## Properties

- [Application](Access.TabControl.Application.md)
- [BackColor](Access.TabControl.BackColor.md)
- [BackShade](Access.TabControl.BackShade.md)
- [BackStyle](Access.TabControl.BackStyle.md)
- [BackThemeColorIndex](Access.TabControl.BackThemeColorIndex.md)
- [BackTint](Access.TabControl.BackTint.md)
- [BorderColor](Access.TabControl.BorderColor.md)
- [BorderShade](Access.TabControl.BorderShade.md)
- [BorderStyle](Access.TabControl.BorderStyle.md)
- [BorderThemeColorIndex](Access.TabControl.BorderThemeColorIndex.md)
- [BorderTint](Access.TabControl.BorderTint.md)
- [BottomPadding](Access.TabControl.BottomPadding.md)
- [ControlType](Access.TabControl.ControlType.md)
- [DisplayWhen](Access.TabControl.DisplayWhen.md)
- [Enabled](Access.TabControl.Enabled.md)
- [EventProcPrefix](Access.TabControl.EventProcPrefix.md)
- [FontBold](Access.TabControl.FontBold.md)
- [FontItalic](Access.TabControl.FontItalic.md)
- [FontName](Access.TabControl.FontName.md)
- [FontSize](Access.TabControl.FontSize.md)
- [FontUnderline](Access.TabControl.FontUnderline.md)
- [FontWeight](Access.TabControl.FontWeight.md)
- [ForeColor](Access.TabControl.ForeColor.md)
- [ForeShade](Access.TabControl.ForeShade.md)
- [ForeThemeColorIndex](Access.TabControl.ForeThemeColorIndex.md)
- [ForeTint](Access.TabControl.ForeTint.md)
- [Gradient](Access.TabControl.Gradient.md)
- [GridlineColor](Access.TabControl.GridlineColor.md)
- [GridlineShade](Access.TabControl.GridlineShade.md)
- [GridlineStyleBottom](Access.TabControl.GridlineStyleBottom.md)
- [GridlineStyleLeft](Access.TabControl.GridlineStyleLeft.md)
- [GridlineStyleRight](Access.TabControl.GridlineStyleRight.md)
- [GridlineStyleTop](Access.TabControl.GridlineStyleTop.md)
- [GridlineThemeColorIndex](Access.TabControl.GridlineThemeColorIndex.md)
- [GridlineTint](Access.TabControl.GridlineTint.md)
- [GridlineWidthBottom](Access.TabControl.GridlineWidthBottom.md)
- [GridlineWidthLeft](Access.TabControl.GridlineWidthLeft.md)
- [GridlineWidthRight](Access.TabControl.GridlineWidthRight.md)
- [GridlineWidthTop](Access.TabControl.GridlineWidthTop.md)
- [Height](Access.TabControl.Height.md)
- [HelpContextId](Access.TabControl.HelpContextId.md)
- [HorizontalAnchor](Access.TabControl.HorizontalAnchor.md)
- [HoverColor](Access.TabControl.HoverColor.md)
- [HoverForeColor](Access.TabControl.HoverForeColor.md)
- [HoverForeShade](Access.TabControl.HoverForeShade.md)
- [HoverForeThemeColorIndex](Access.TabControl.HoverForeThemeColorIndex.md)
- [HoverForeTint](Access.TabControl.HoverForeTint.md)
- [HoverShade](Access.TabControl.HoverShade.md)
- [HoverThemeColorIndex](Access.TabControl.HoverThemeColorIndex.md)
- [HoverTint](Access.TabControl.HoverTint.md)
- [InSelection](Access.TabControl.InSelection.md)
- [IsVisible](Access.TabControl.IsVisible.md)
- [Layout](Access.TabControl.Layout.md)
- [LayoutID](Access.TabControl.LayoutID.md)
- [Left](Access.TabControl.Left.md)
- [LeftPadding](Access.TabControl.LeftPadding.md)
- [MultiRow](Access.TabControl.MultiRow.md)
- [Name](Access.TabControl.Name.md)
- [OldValue](Access.TabControl.OldValue.md)
- [OnChange](Access.TabControl.OnChange.md)
- [OnClick](Access.TabControl.OnClick.md)
- [OnDblClick](Access.TabControl.OnDblClick.md)
- [OnKeyDown](Access.TabControl.OnKeyDown.md)
- [OnKeyPress](Access.TabControl.OnKeyPress.md)
- [OnKeyUp](Access.TabControl.OnKeyUp.md)
- [OnMouseDown](Access.TabControl.OnMouseDown.md)
- [OnMouseMove](Access.TabControl.OnMouseMove.md)
- [OnMouseUp](Access.TabControl.OnMouseUp.md)
- [Pages](Access.TabControl.Pages.md)
- [Parent](Access.TabControl.Parent.md)
- [PressedColor](Access.TabControl.PressedColor.md)
- [PressedForeColor](Access.TabControl.PressedForeColor.md)
- [PressedForeShade](Access.TabControl.PressedForeShade.md)
- [PressedForeThemeColorIndex](Access.TabControl.PressedForeThemeColorIndex.md)
- [PressedForeTint](Access.TabControl.PressedForeTint.md)
- [PressedShade](Access.TabControl.PressedShade.md)
- [PressedThemeColorIndex](Access.TabControl.PressedThemeColorIndex.md)
- [PressedTint](Access.TabControl.PressedTint.md)
- [Properties](Access.TabControl.Properties.md)
- [RightPadding](Access.TabControl.RightPadding.md)
- [Section](Access.TabControl.Section.md)
- [Shape](Access.TabControl.Shape.md)
- [ShortcutMenuBar](Access.TabControl.ShortcutMenuBar.md)
- [StatusBarText](Access.TabControl.StatusBarText.md)
- [Style](Access.TabControl.Style.md)
- [TabFixedHeight](Access.TabControl.TabFixedHeight.md)
- [TabFixedWidth](Access.TabControl.TabFixedWidth.md)
- [TabIndex](Access.TabControl.TabIndex.md)
- [TabStop](Access.TabControl.TabStop.md)
- [Tag](Access.TabControl.Tag.md)
- [ThemeFontIndex](Access.TabControl.ThemeFontIndex.md)
- [Top](Access.TabControl.Top.md)
- [TopPadding](Access.TabControl.TopPadding.md)
- [UseTheme](Access.TabControl.UseTheme.md)
- [Value](Access.TabControl.Value.md)
- [VerticalAnchor](Access.TabControl.VerticalAnchor.md)
- [Visible](Access.TabControl.Visible.md)
- [Width](Access.TabControl.Width.md)

## See also

- [Access Object Model Reference](overview/Access/object-model.md)


[!include[Support and feedback](~/includes/feedback-boilerplate.md)]

"
Class {
	#name : #JinControlTabControl,
	#superclass : #JinControlAbstractTabControl,
	#category : #'Jindao-DomainObjects-GeneratedControls'
}

{ #category : #generated }
JinControlTabControl class >> mappedTypeName [
	^#'_TabControl'
]

{ #category : #generated }
JinControlTabControl >> acceptVisitor: aVisitor [
	^ aVisitor visitTabControl: self
]

{ #category : #'property - generated' }
JinControlTabControl >> application [
<getter>
	^ (handle propertyNamed: #'Application' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backColor [
<getter>
	^ (handle propertyNamed: #'BackColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BackColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backShade [
<getter>
	^ (handle propertyNamed: #'BackShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BackShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backStyle [
<getter>
	^ (handle propertyNamed: #'BackStyle' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backStyle: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BackStyle' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'BackThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BackThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backTint [
<getter>
	^ (handle propertyNamed: #'BackTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> backTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BackTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderColor [
<getter>
	^ (handle propertyNamed: #'BorderColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BorderColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderShade [
<getter>
	^ (handle propertyNamed: #'BorderShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BorderShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderStyle [
<getter>
	^ (handle propertyNamed: #'BorderStyle' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderStyle: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BorderStyle' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'BorderThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BorderThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderTint [
<getter>
	^ (handle propertyNamed: #'BorderTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> borderTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BorderTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> bottomPadding [
<getter>
	^ (handle propertyNamed: #'BottomPadding' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> bottomPadding: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'BottomPadding' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> controlType [
<getter>
	^ (handle propertyNamed: #'ControlType' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> controlType: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ControlType' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> displayWhen [
<getter>
	^ (handle propertyNamed: #'DisplayWhen' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> displayWhen: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'DisplayWhen' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> enabled [
<getter>
	^ (handle propertyNamed: #'Enabled' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> enabled: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Enabled' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> eventProcPrefix [
<getter>
	^ (handle propertyNamed: #'EventProcPrefix' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> eventProcPrefix: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'EventProcPrefix' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontBold [
<getter>
	^ (handle propertyNamed: #'FontBold' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontBold: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'FontBold' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontItalic [
<getter>
	^ (handle propertyNamed: #'FontItalic' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontItalic: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'FontItalic' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontName [
<getter>
	^ (handle propertyNamed: #'FontName' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontName: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'FontName' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontSize [
<getter>
	^ (handle propertyNamed: #'FontSize' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontSize: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'FontSize' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontUnderline [
<getter>
	^ (handle propertyNamed: #'FontUnderline' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontUnderline: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'FontUnderline' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontWeight [
<getter>
	^ (handle propertyNamed: #'FontWeight' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> fontWeight: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'FontWeight' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreColor [
<getter>
	^ (handle propertyNamed: #'ForeColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ForeColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreShade [
<getter>
	^ (handle propertyNamed: #'ForeShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ForeShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'ForeThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ForeThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreTint [
<getter>
	^ (handle propertyNamed: #'ForeTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> foreTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ForeTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gradient [
<getter>
	^ (handle propertyNamed: #'Gradient' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gradient: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Gradient' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineColor [
<getter>
	^ (handle propertyNamed: #'GridlineColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineShade [
<getter>
	^ (handle propertyNamed: #'GridlineShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleBottom [
<getter>
	^ (handle propertyNamed: #'GridlineStyleBottom' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleBottom: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineStyleBottom' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleLeft [
<getter>
	^ (handle propertyNamed: #'GridlineStyleLeft' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleLeft: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineStyleLeft' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleRight [
<getter>
	^ (handle propertyNamed: #'GridlineStyleRight' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleRight: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineStyleRight' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleTop [
<getter>
	^ (handle propertyNamed: #'GridlineStyleTop' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineStyleTop: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineStyleTop' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'GridlineThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineTint [
<getter>
	^ (handle propertyNamed: #'GridlineTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthBottom [
<getter>
	^ (handle propertyNamed: #'GridlineWidthBottom' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthBottom: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineWidthBottom' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthLeft [
<getter>
	^ (handle propertyNamed: #'GridlineWidthLeft' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthLeft: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineWidthLeft' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthRight [
<getter>
	^ (handle propertyNamed: #'GridlineWidthRight' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthRight: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineWidthRight' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthTop [
<getter>
	^ (handle propertyNamed: #'GridlineWidthTop' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> gridlineWidthTop: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'GridlineWidthTop' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> height [
<getter>
	^ (handle propertyNamed: #'Height' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> height: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Height' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> helpContextId [
<getter>
	^ (handle propertyNamed: #'HelpContextId' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> helpContextId: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HelpContextId' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> horizontalAnchor [
<getter>
	^ (handle propertyNamed: #'HorizontalAnchor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> horizontalAnchor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HorizontalAnchor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverColor [
<getter>
	^ (handle propertyNamed: #'HoverColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeColor [
<getter>
	^ (handle propertyNamed: #'HoverForeColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverForeColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeShade [
<getter>
	^ (handle propertyNamed: #'HoverForeShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverForeShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'HoverForeThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverForeThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeTint [
<getter>
	^ (handle propertyNamed: #'HoverForeTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverForeTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverForeTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverShade [
<getter>
	^ (handle propertyNamed: #'HoverShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'HoverThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverTint [
<getter>
	^ (handle propertyNamed: #'HoverTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> hoverTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'HoverTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> inSelection [
<getter>
	^ (handle propertyNamed: #'InSelection' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> inSelection: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'InSelection' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> isVisible [
<getter>
	^ (handle propertyNamed: #'IsVisible' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> isVisible: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'IsVisible' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> layout [
<getter>
	^ (handle propertyNamed: #'Layout' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> layoutID [
<getter>
	^ (handle propertyNamed: #'LayoutID' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> left [
<getter>
	^ (handle propertyNamed: #'Left' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> left: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Left' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> leftPadding [
<getter>
	^ (handle propertyNamed: #'LeftPadding' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> leftPadding: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'LeftPadding' withArguments: {aParam1} ).

]

{ #category : #'method - generated' }
JinControlTabControl >> move: aLeft top: aTop width: aWidth height: aHeight [
<method>
"This method can be called with optional parameters. Top,Width,Height"
	^ (handle dispatch: #'Move' withArguments: {aLeft . aTop . aWidth . aHeight} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> multiRow [
<getter>
	^ (handle propertyNamed: #'MultiRow' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> multiRow: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'MultiRow' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> name [
<getter>
	^ (handle propertyNamed: #'Name' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> name: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Name' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> oldValue [
<getter>
	^ (handle propertyNamed: #'OldValue' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onChange [
<getter>
	^ (handle propertyNamed: #'OnChange' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onChange: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnChange' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onClick [
<getter>
	^ (handle propertyNamed: #'OnClick' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onClick: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnClick' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onDblClick [
<getter>
	^ (handle propertyNamed: #'OnDblClick' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onDblClick: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnDblClick' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onKeyDown [
<getter>
	^ (handle propertyNamed: #'OnKeyDown' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onKeyDown: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnKeyDown' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onKeyPress [
<getter>
	^ (handle propertyNamed: #'OnKeyPress' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onKeyPress: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnKeyPress' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onKeyUp [
<getter>
	^ (handle propertyNamed: #'OnKeyUp' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onKeyUp: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnKeyUp' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onMouseDown [
<getter>
	^ (handle propertyNamed: #'OnMouseDown' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onMouseDown: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnMouseDown' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onMouseMove [
<getter>
	^ (handle propertyNamed: #'OnMouseMove' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onMouseMove: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnMouseMove' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onMouseUp [
<getter>
	^ (handle propertyNamed: #'OnMouseUp' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> onMouseUp: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'OnMouseUp' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pages [
<getter>
	^ (handle propertyNamed: #'Pages' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> parent [
<getter>
	^ (handle propertyNamed: #'Parent' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedColor [
<getter>
	^ (handle propertyNamed: #'PressedColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeColor [
<getter>
	^ (handle propertyNamed: #'PressedForeColor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeColor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedForeColor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeShade [
<getter>
	^ (handle propertyNamed: #'PressedForeShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedForeShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'PressedForeThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedForeThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeTint [
<getter>
	^ (handle propertyNamed: #'PressedForeTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedForeTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedForeTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedShade [
<getter>
	^ (handle propertyNamed: #'PressedShade' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedShade: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedShade' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedThemeColorIndex [
<getter>
	^ (handle propertyNamed: #'PressedThemeColorIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedThemeColorIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedThemeColorIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedTint [
<getter>
	^ (handle propertyNamed: #'PressedTint' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> pressedTint: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'PressedTint' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> properties [
<getter>
	^ (handle propertyNamed: #'Properties' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> rightPadding [
<getter>
	^ (handle propertyNamed: #'RightPadding' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> rightPadding: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'RightPadding' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> section [
<getter>
	^ (handle propertyNamed: #'Section' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> section: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Section' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> shape [
<getter>
	^ (handle propertyNamed: #'Shape' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> shape: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Shape' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> shortcutMenuBar [
<getter>
	^ (handle propertyNamed: #'ShortcutMenuBar' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> shortcutMenuBar: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ShortcutMenuBar' withArguments: {aParam1} ).

]

{ #category : #'method - generated' }
JinControlTabControl >> sizeToFit [
<method>
	^ (handle dispatch: #'SizeToFit' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> statusBarText [
<getter>
	^ (handle propertyNamed: #'StatusBarText' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> statusBarText: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'StatusBarText' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> style [
<getter>
	^ (handle propertyNamed: #'Style' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> style: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Style' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabFixedHeight [
<getter>
	^ (handle propertyNamed: #'TabFixedHeight' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabFixedHeight: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'TabFixedHeight' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabFixedWidth [
<getter>
	^ (handle propertyNamed: #'TabFixedWidth' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabFixedWidth: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'TabFixedWidth' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabIndex [
<getter>
	^ (handle propertyNamed: #'TabIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'TabIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabStop [
<getter>
	^ (handle propertyNamed: #'TabStop' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tabStop: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'TabStop' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tag [
<getter>
	^ (handle propertyNamed: #'Tag' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> tag: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Tag' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> themeFontIndex [
<getter>
	^ (handle propertyNamed: #'ThemeFontIndex' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> themeFontIndex: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'ThemeFontIndex' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> top [
<getter>
	^ (handle propertyNamed: #'Top' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> top: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Top' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> topPadding [
<getter>
	^ (handle propertyNamed: #'TopPadding' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> topPadding: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'TopPadding' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> useTheme [
<getter>
	^ (handle propertyNamed: #'UseTheme' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> useTheme: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'UseTheme' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> value [
<getter>
	^ (handle propertyNamed: #'Value' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> value: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Value' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> verticalAnchor [
<getter>
	^ (handle propertyNamed: #'VerticalAnchor' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> verticalAnchor: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'VerticalAnchor' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> visible [
<getter>
	^ (handle propertyNamed: #'Visible' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> visible: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Visible' withArguments: {aParam1} ).

]

{ #category : #'property - generated' }
JinControlTabControl >> width [
<getter>
	^ (handle propertyNamed: #'Width' ).

]

{ #category : #'property - generated' }
JinControlTabControl >> width: aParam1 [
<setter>
		
	^ (handle propertyNamed: #'Width' withArguments: {aParam1} ).

]
