Class {
	#name : #JinCrossProjectDependancy,
	#superclass : #Object,
	#instVars : [
		'type',
		'name'
	],
	#category : #'Jindao-Metrics'
}

{ #category : #'as yet unclassified' }
JinCrossProjectDependancy >> allDependencies [
	^ {}
]

{ #category : #'as yet unclassified' }
JinCrossProjectDependancy >> name: aString [ 
	name := aString
]

{ #category : #'as yet unclassified' }
JinCrossProjectDependancy >> type: aString [ 
	type := aString
]
